import {dir} from 'i18next'
import {languages, LanguageType} from "@/app/i18n/settings";

import type {Metadata} from "next";
import {Inter} from "next/font/google";
import '@digdir/designsystemet-css';
import '@digdir/designsystemet-theme';
import "../globals.scss";
import Providers from "@/app/providers";
import {FC, PropsWithChildren} from "react";
import ClientTranslationProvider from "@/app/i18n/ClientTranslationProvider";
import ServerTranslationWrapper from "@/app/i18n/ServerTranslationWrapper";

export async function generateStaticParams() {
    return languages.map((lng) => ({lng}))
}


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


interface RootLayoutProps extends PropsWithChildren {
    params: {
        lang: string;
    }

}

const RootLayout: FC<RootLayoutProps> = (props) => {
    return (
        <html lang={props.params.lang} dir={dir(props.params.lang)}>
        <body className={inter.className}>
        <ClientTranslationProvider lang={props.params.lang as LanguageType}>
        {/*<ClientTranslationProvider>*/}
            <Providers>{props.children}</Providers>
        {/*</ClientTranslationProvider>*/}
        </ClientTranslationProvider>
        </body>
        </html>
    );
}
export default RootLayout