import {dir} from 'i18next'
import {languages, LanguageType} from "@/app/i18n/settings";

import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import '@digdir/designsystemet-css';
import '@digdir/designsystemet-theme';
import "@/app/globals.scss";
import ReactQueryProvider from "@/app/providers";
import {FC, PropsWithChildren} from "react";
import ClientTranslationProvider from "@/app/i18n/ClientTranslationProvider";
import {LoadingProvider} from "@/components/loading-wrapper/LoadingContext";
import LoadingIndicationWrapper from "@/components/loading-wrapper/LoadingIndicationWrapper";
import Footer from "@/components/layout/footer/footer";
import Header from "@/components/layout/header/header";
import PrefetchWrapper from "@/components/loading-wrapper/PrefetchWrapper";

export async function generateStaticParams() {
    return languages.map((lng) => ({lng}))
}


const inter = Roboto({weight: ['100', '300', '400', '500', '700', '900'], subsets: ['latin']});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


interface RootLayoutProps extends PropsWithChildren {
    params: {
        lang: string;
    }

}

const RootLayout: FC<RootLayoutProps> = (props) => {

    return (
        <html lang={props.params.lang} dir={dir(props.params.lang)}>
        <body className={inter.className}>
        {props.children}
        </body>
        </html>
    );
}
export default RootLayout